
import './globals.css'
import { Inter, Cinzel } from 'next/font/google'

const cinzel = Cinzel({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={cinzel.className}>{children}</body>
    </html>
  )
}
